### ISSUE TITLE
Add stubs for the pgsql extension

### ISSUE THREAD

**Issue by kocsismate** [php/php-tasks#10]
Since the [stubs initiative](https://externals.io/message/106522) had been started, stub definitions were added for [nearly all built-in functions and methods](https://github.com/php/php-src/pulls?q=is%3Apr+label%3AStubs+is%3Aclosed+), except for ext/pgsql.

**Comment by nikic** [comment]
Done in https://github.com/php/php-src/commit/47688ab6d97f0efc004a12ad10174162ef4d2277. This was "fun".
