### ISSUE TITLE
Improve Azure pipelines to skip some changes

### ISSUE THREAD

**Issue by carusogabriel** [php/php-tasks#17]
We can improve

https://github.com/php/php-src/blob/47e4001976f3ff85a6d479df39dc82d4ceb18b19/azure-pipelines.yml#L7-L12

to skip builds for changes in text-only files :)

**Comment by himanshu007-creator** [comment]
can i work on this issue?

**Comment by nikic** [comment]
I'm actually not sure what this issue is suggesting ... doesn't the referenced part of azure-pipelines.yml already skip doc-only changes?

**Comment by carusogabriel** [comment]
@nikic What I meant was documentation, `README.md`s in the extensions, etc.

@himanshu007-creator Sure, go ahead!

**Comment by himanshu007-creator** [comment]
> @nikic What I meant was documentation, `README.md`s in the extensions, etc.
> 
> @himanshu007-creator Sure, go ahead!

https://github.com/php/php-src/pull/6876
