### ISSUE TITLE
Move Windows testing to Azure Pipelines

### ISSUE THREAD

**Issue by nikic** [php/php-tasks#21]
We only have two parallel builds on AppVeyor, and additionally that service has unworkable cancellation behavior (there are no "rolling builds"). We should try moving this to Azure. There is some old work on this at https://github.com/php/php-src/pull/4223 that might be reused.

**Comment by nikic** [comment]
I did a quick experiment in https://github.com/php/php-src/pull/6463, but don't plan to continue working on this myself. For some reason the build is also very slow, but possibly that's avoidable (e.g. if it's due to skipif timeouts or so) :/

**Comment by Girgias** [comment]
Maybe we could use GitHub actions?
@shivammathur seems to have figured how to build it via the following repo https://github.com/shivammathur/php-builder-windows

**Comment by Girgias** [comment]
We are now running Windows on GHA
