### ISSUE TITLE
Remove deprecated functionality in PHP 9

### ISSUE THREAD

**Issue by cmb69** [php/php-tasks#27]
* [ ] [base_convert() and friends should thrown on invalid characters](https://wiki.php.net/rfc/base_convert_improvements)
* [ ] ZIP Procedural API
* [ ] ``ZipArchive::open()`` empty file is deprecated
* [ ] Returning ``bool`` for array comparison functions
* [ ] ``Session callback must have a return value of type bool``
* [ ] ``get_defined_functions()`` boolean argument ``exclude_disabled`` has no effect
* [ ] ``CURLPIPE_HTTP1``
* [ ] `allow_url_include`
* [ ] `"${var}"` and `"${expr}"` stlye string interpolation

**Comment by jensdenies** [comment]
Hi @cmb69, @cjbj,

Would it be a good idea to add the deprecated OCI aliases to this list, since they have been soft deprecated a long time ago and hard deprecated in PHP 8.0 (https://github.com/php/php-src/pull/5589)?

**Comment by cjbj** [comment]
@jensdenies seems like busy work.  But if the lack of 'niceness' is itching you, it can be done.

**Comment by cmb69** [comment]
> Would it be a good idea to add the deprecated OCI aliases to this list, since they have been soft deprecated a long time ago and hard deprecated in PHP 8.0

Given that OCI has been unbundled, that is up to maintainers of https://github.com/php/pecl-database-oci8.

Anyhow, this issue has (some) overlap with https://wiki.php.net/rfc#pending_implementationlanding. The latter seems to be the appropriate place to track that, so I'm closing this ticket.
