### ISSUE TITLE
Add missing CI for extensions

### ISSUE THREAD

**Issue by nikic** [php/php-tasks#29]
The following extensions currently do not have CI testing or only incomplete testing. These should be tested on Azure Pipelines Linux x64 configuration if possible.

 * oci8
   * [x] Build (https://github.com/php/php-src/pull/6604)
   * [x] Test
 * pdo_dblib
   * [x] Build (https://github.com/php/php-src/pull/6569)
   * [x] Test (https://github.com/php/php-src/pull/6569)
 * pdo_firebird
   * [x] Build (https://github.com/php/php-src/pull/6529)
   * [x] Test (https://github.com/php/php-src/pull/12677)
 * pdo_oci
   * [x] Build (https://github.com/php/php-src/pull/6604)
   * [x] Test

These extensions are fully tested on Windows (AppVeyor). Having additional testing on Linux would be valuable, but is not critical:

 * odbc
   * [x] Build (using unixodbc)
   * [x] Test (https://github.com/php/php-src/pull/11938)
 * pdo_odbc
   * [x] Build (https://github.com/php/php-src/pull/6528)
   * [x] Test

**Comment by cmb69** [comment]
FWIW, ext/odbc and ext/pdo_odbc are built and tested on AppVeyor against MS SQLServer. Testing against other databases would certainly be *highly* desireable, but likely many tests would fail (I ran the tests against MySQL, and roughly half of them failed).

**Comment by nikic** [comment]
@cmb69 Thanks for the information, I was not aware that there are tested on AppVeyor. Having these tested on Linux and other DBs would be good, but it's reassuring that at least we have them somewhere...

**Comment by nikic** [comment]
I've added builds for PDO ODBC and PDO Firebird. PDO DBlib is also easy to build, but each test waits for a ~10s timeout, so we'd have to actually set up the server side for that to be feasible.

**Comment by nikic** [comment]
PDO DBLib build & test has been added in https://github.com/php/php-src/pull/6569.

**Comment by nikic** [comment]
OCI and PDO OCI build has been added in https://github.com/php/php-src/pull/6604.

**Comment by kocsismate** [comment]
ext/odbc and ext/pdo_odbc tests are enabled on LInux, test coverage is significantly improved: https://github.com/php/php-src/pull/11938

**Comment by SakiTakamachi** [comment]
pdo_oci has been decided to be unbundled, and tests for pdo_firebird have been added through the following pull request.

https://github.com/php/php-src/pull/12677

Therefore, this task may be considered complete.
