### ISSUE TITLE
Test OCI8 on CI

### ISSUE THREAD

**Issue by nikic** [php/php-tasks#5]
The oci8 extension is currently not tested on CI. Per https://github.com/php/php-src/pull/5714#issuecomment-644591885 it used to be tested on gcov, but gcov is no longer used since PHP 7.4.

To test oci8, we need to have OracleDB XE available on one of our public CI providers (Travis, Azure Pipelines or AppVeyor). It seems like this is not really possible right now (in a legal way), but based on the discussion in https://github.com/oracle/docker-images/issues/1156 it might be possible in the future.

**Comment by nikic** [comment]
We now at least test that OCI8/PDO_OCI build (#29).

**Comment by mvorisek** [comment]
This issue can be closed, CI for oci8/pdo_oci was added by me in https://github.com/php/php-src/pull/8348

**Comment by mvorisek** [comment]
@kocsismate should be also marked as done in https://github.com/php/php-tasks/issues/29
