### ISSUE TITLE
Use ZPP Union type checks whenever possible

### ISSUE THREAD

**Issue by Girgias** [php/php-tasks#7]
With the introduction of union types in PHP 8.0, ZPP got some added capabilities for common union types namely:
- ``array|object``
- ``string|array``
- ``string|int``

We should aim to use them whenever possible as they handle typing behaviour in weak/strict mode more consistently than when implemented manually (if done at all).

A non exhaustive list of extensions which can benefit from this:
- [ ] DBA
- [ ] Intl
- [ ] PCRE (php/php-src#5750)
- [ ] SNMP
- [ ] standard
- [ ] Tidy
- [ ] XSL

**Comment by nikic** [comment]
Is there anything actionable still left here? I think @kocsismate already did this where possible.

**Comment by kocsismate** [comment]
I completely ignored the dba and imap extensions, so it might be possible that there are some candidates there. Also, if I remember well, it is now possible to declare types consisting of multiple classes, so we could add the necessary ZPP macros for this purpose (one example: `RecursiveIterator|IteratorAggregate`). And we haven't added ZPP for too weird or too rare union types like (`FFI\CData|int|float|bool|null`, `callable|int`, `OpenSSLAsymmetricKey|OpenSSLCertificate|array|string `).

But all in all, we are quite good at using ZPP. Actually, only ~250 parameters are not declared in the stubs (excluding the ones which contain resources in their types, as well as out parameters). So in my opinion, we are practically 99% done :)

**Comment by Girgias** [comment]
Imap *should* be fine, and DBA is just a lost cause...

Closing as it seems we've reasonably covered all cases
