### ISSUE TITLE
ext/zip/tests/bug53885.phpt fails on 7.4 on macos

### ISSUE THREAD

**Issue by nikic** [php/php-tasks#8]
The test ext/zip/tests/bug53885.phpt fails on PHP 7.4 (but not master!) on macos with the diff:

> 001+ Warning: ZipArchive::locateName(): Invalid or uninitialized Zip object in /Users/runner/runners/2.170.1/work/1/s/ext/zip/tests/bug53885.php on line 7
> 002+ 
> 003+ Warning: ZipArchive::statName(): Invalid or uninitialized Zip object in /Users/runner/runners/2.170.1/work/1/s/ext/zip/tests/bug53885.php on line 8

@remicollet Do you know why this would happen on 7.4 only? It started happening only recently.

**Comment by remicollet** [comment]
This should not happen.
I notice the same error with libzip 1.7.0 which is totally broken

Which libzip version is it ?

In short libzip 1.7.0 don't have any of the LIBZIP_VERSION_* macro, which make its use impossible

libzip 1.7.1 is OK.

**Comment by remicollet** [comment]
Perhaps we can add

```
#if ! defined (LIBZIP_VERSION_MAJOR)
#error Borken libzip update to 1.7.1
#endif
```

**Comment by nikic** [comment]
@remicollet Thanks for the quick reply! I checked the build log and it does indeed say:

> Warning: libzip 1.7.0 is already installed and up-to-date
> To reinstall 1.7.0, run `brew reinstall libzip`

Probably we need to force macos CI to update this package in some way.

**Comment by remicollet** [comment]
For memory we have same issue with 1.3.1
* 1.3.1 released on 2017-11-19
* 1.3.2 released on 2017-11-22 so only 3 days

And:

* 1.7.0 released on 2020-06-05
* 1.7.1 released on 2020-06-13 so only 1 week

**Comment by nikic** [comment]
Proposed fix: https://github.com/php/php-src/pull/5737

**Comment by remicollet** [comment]
Sorry, was working on another fix (at configure time, which can be better), so miss your PR.
BTW, both make sense

**Comment by nikic** [comment]
Fixed by:
 * https://github.com/php/php-src/commit/090bddb93488b6bcf411e970afe77d96f86f4ac8 libzip version on our macos CI
 * https://github.com/php/php-src/commit/f3e6b123dc5da6a92960fbe21000b53a3450e64a configure check for broken libzip version

Thanks for your help @remicollet!
